config/routes.rb
Foroldy::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  resources :pages, except: :show

  devise_for :users

  match "aboutus" => "aboutus#index"

  namespace :admin do
    root to: "main#index"
    resources :pages
  end

  get "welcome/index"

  get "welcome/contruction"

  get "welcome/error"

  root to: "welcome#index"
  get 'p/:id', to:  'pages#show', as: :page

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset
  include Ckeditor::Orm::Mongoid::AssetBase

  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/page.rb
class Page
  include Mongoid::Document
  field :name, type: String
  field :permalink, type: String
  field :content, type: String
  validates_uniqueness_of :permalink

  def to_param
    permalink
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable , :confirmable

  ## Database authenticatable
  field :name,              :type => String, :default => ""
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  layout 'aboutus'
  def index
  end
end

app/controllers/admin/main_controller.rb
class Admin::MainController < ApplicationController
  layout "admin"
  def index
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  layout 'admin'
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    #@page = Page.find(params[:id])
    @page = Page.where(permalink: params[:id]).first
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    #@page = Page.find(params[:id])
    @page = Page.where(permalink: params[:id]).first
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to [:admin,@page], notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to [:admin,@page], notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to admin_pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource
  protect_from_forgery
  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'page'
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    #@page = Page.find(params[:id])
    @page = Page.where(permalink: params[:id]).first
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"
  def index
  end

  def contruction
  end

  def error
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/aboutus/index.html.erb
<h1>Aboutus#index</h1>
<p>Find me in app/views/aboutus/index.html.erb</p>

app/views/admin/main/index.html.erb
<h1>Admin::Main#index</h1>
<p>Find me in app/views/admin/main/index.html.erb</p>

app/views/admin/pages/_form.html.erb
<%= form_for([:admin,@page]) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field large">
    <%= f.label :name %>
    <%= f.text_field :name , :class=>"span8  input-xlarge"%>
  </div>
  <div class="field large">
    <%= f.label :permalink %>
    <%= f.text_field :permalink, :class=>"span8  input-xlarge" %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :ckeditor => {:uiColor => "#AADC6E", :toolbar => "mini"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@page] %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<h1>Listing pages</h1>

<table id="pages">
  <thead>
  <tr>
    <th>Name</th>
    <th>Permalink</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= page.permalink %></td>
    <td><%= page.content %></td>
    <td><%= link_to 'Show', [:admin,page] %></td>
    <td><%= link_to 'Edit', edit_admin_page_path(page) %></td>
    <td><%= link_to 'Destroy', [:admin,page], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
 </tbody>
</table>

<br />

<%= link_to 'New Page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<div class="pageheader">
  <h2><%= @page.name %></h2>
 <hr class="dashed">
</div>
<p>
  <b>Permalink:</b>
  <%= @page.permalink %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>


<%= link_to 'Edit', edit_admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>

app/views/layouts/aboutus.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Foroldy" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" style="margin-right: 20px; color: #E717CD;" href="/">Foroldy</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <h4 style="color: #FFFFFF; float: left; margin-right: 30px;">สถานะโครงการ</h4>
                <div class="status" style="margin-right: 30px;">
                  <div class="number-label" >
                    ผู้สูงอายุ:  212 คน
                  </div>
                </div>
                <div class="status" style="margin-right: 30px;">
                  <div class="number-label">
                    อุปกรณ์:  100 ชิ้น
                  </div>
                </div>
                <div class="status" >
                  <div class="number-label">
                    อาสาสมัคร:  30 คน
                  </div>
                </div>

            </ul>
            <ul class="nav pull-right">
              <li><%= link_to "ประสงค์บริจาค", "/path1"  %></li>
              <li><%= link_to "แจ้งขอรับบริจาค", "/path2"  %></li>
              <li><%= link_to "ติดต่อเรา", "/aboutus"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
      <div class="container" style="margin-top: 30px;">
        <div class="row">
        <div class="span5">
          <h4>โครงการเพื่อผู้สูงอายุ :  Foroldy Project </h4>
          <p>
            55/238 ซอยหมู่บ้านสราญรมย์(ซอย 7)  ถนนนวลจันทร์ เขตคลองกุ่ม เขตบึงกุ่ม กรุงเทพฯ 10230
          </p>
          <p> โทร 087 591 5658 , 086 046 2925, 087  591 5658 </p>
        </div>
        <div class="span7">
<iframe width="600" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?msa=0&amp;msid=209474251122505523802.0004d965b93df164bdb39&amp;ie=UTF8&amp;ll=13.808284,100.647018&amp;spn=0,0&amp;t=m&amp;output=embed"></iframe><br /><small>ดู <a href="https://maps.google.com/maps/ms?msa=0&amp;msid=209474251122505523802.0004d965b93df164bdb39&amp;ie=UTF8&amp;ll=13.808284,100.647018&amp;spn=0,0&amp;t=m&amp;source=embed" style="color:#0000FF;text-align:left">ร้านคุณตา คุณยาย</a> ในแผนที่ขนาดใหญ่กว่า</small>
        </div>

        </div> <!--row -->
      </div> <!--container -->


    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="span3">
            <h3>เชื่อมโยง</h3>
            <ul class="animated" style="list-style: none">
              <li class="heart"><a href="http://www.unltd.in.th/" target="_blank">UnLtd Thailand</a></li>
            </ul>
          </div>
          <div class="span3">
            <h3>เกี่ยวกับโครงการ</h3>
            <ul class="animated" style="list-style: none">
              <li class="heart"><a href="#">นโยบาย</a></li>
              <li class="heart"><a href="#">เงือนไขการขอรับบริการ</a></li>
              <li class="heart"><a href="#">ถามตอบ</a></li>
              <li class="heart"><a href="#">ติดต่อเรา</a></li>
            </ul>
          </div>
          <div class="span3">
            <h3>เครือข่ายสังคมออนไลน์</h3>
            <ul class="animated" style="list-style: none">
              <li class="heart"><a href="http://www.facebook.com/Foroldy" target="_blank">Facebook</a></li>
              <li class="heart">
<a href="https://twitter.com/foroldy" class="twitter-follow-button" data-show-count="false">Follow @foroldy</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
              </li>
            </ul>
          </div>
          <div class="span3">
            <h3>ลงทะเบียน</h3>
            <p>ท่านสามารถร่วมเป็นส่วนหนึ่งของโครงการ Foroldy ด้วยการลงทะเบียนเพื่อรับข้อมูลข่าวสาร ความเคลื่อนไหว และ กิจกรรมที่เป็นประโยชน์ของโครงการ</p>
            <form>
              <input type="text" name="subscribe" placeholder="Your Email" class="span3">
              <button class="btn btn-primary">Subscribe</button>
            </form>
          </div>
        </div>
      </div>
    </div> <!-- footer -->

    <div id="copywrite">
      <div class="container">
        <div class="row">
          <div class="span12">
            <p>&copy; 2013 Foroldy Project <span class="pull-right" id="totop">Back to Top <i class="icon-arrow-up icon-white"></i></span></p>
          </div>
        </div>
      </div>
    </div> <!--copywrite -->
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/admin.html.erb
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Admin Section: Foroldy" %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
<![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>

<!-- For third-generation iPad with high-resolution Retina display: -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body class="fullpage admin">
    <div class="navbar navbar-inverse navbar-fixed-top" style="height: 30px">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" style="margin-right: 20px;color: #E717CD;" href="/">Foroldy</a>
          <div class="container nav-collapse">
            <ul class="nav">
            </ul>
            <ul class="nav pull-right">
             <% if user_signed_in? %>
              <li>
                Logged in as <strong><%= current_user.email %></strong>.
              </li>
              <li>
                <%= link_to 'Edit profile', edit_user_registration_path %> |
              </li>
              <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
              </li>
              <% else %>
              <li>
                <%= link_to "Sign up", new_user_registration_path %> |
              </li>
              <li>
                <%= link_to "Login", new_user_session_path %>
              </li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div> <!-- navbar -->

    <div class="wrapper" id="content">
      <div class="container">
        <div class="row box">
          <div class="span3  ">
            <h4>ส่วนผู้ดูแลระบบ</h4>
            <ul class="nav nav-list">
              <li class="nav-headerh4">จัดการเนื้อหา</li>
              <li class="active"><a href="#"><i class="icon-white icon-home"></i>จัดการหน้าแรก</a></li>
              <li><a href="/admin/pages/"><i class="icon-book"></i>เนื้อหา page</a></li>
              <li><a href="#"><i class="icon-pencil"></i>ประกาศกิจกรรม</a></li>
              <li><a href="#"><i class="icon-pencil"></i>ปฎิทิน</a></li>
              <li class="nav-headerh4">บริหารจัดการระบบ</li>
              <li><a href="#"><i class="icon-user"></i>ผู้สูงอายุ</a></li>
              <li><a href="#"><i class="icon-user"></i>อาสาสมัคร</a></li>
              <li><a href="#"><i class="icon-user"></i>บริการผู้สูงอายุ</a></li>
              <li><a href="#"><i class="icon-user"></i>รับสินค้าเข้า</a></li>
              <li><a href="#"><i class="icon-cog"></i>จำหน่ายสินค้า</a></li>
              <li class="divider"></li>
              <li><a href="#"><i class="icon-flag"></i>รายการซ่อม</a></li>
              <li><a href="#"><i class="icon-flag"></i>เรื่องราวรับบริจาค</a></li>
            </ul>
          </div>

          <div class="span8 ">
            <%= yield  %>
          </div>
        </div>
      </div>
    </div> <!--content -->



    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Foroldy" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body class="full">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Foroldy</a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to 'Edit profile', edit_user_registration_path %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path %> |
                <%= link_to "Login", new_user_session_path %>
              <% end %>


            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>





    <div class="container" style="margin-top: 80px;">
      <div class="row">
        <div class="span6  transparent">
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  <div id="copy">
    <div class="container">
      <div class="row">
        <div class="span12">
          <p>&copy; 2013 Foroldy Social Enterprise </p>
        </div>
      </div>
    </div>
  </div> <!--copywrite -->
  <!-- Javascripts
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <%= javascript_include_tag "application" %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Permalink</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= page.permalink %></td>
    <td><%= page.content %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<div class="pageheader">
  <h2><%= @page.name %></h2>
 <hr class="dashed">
</div>
<p>
  <b>Permalink:</b>
  <%= @page.permalink %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/welcome/contruction.html.erb
<h1>Welcome#contruction</h1>
<p>Find me in app/views/welcome/contruction.html.erb</p>

app/views/welcome/error.html.erb
<h1>Welcome#error</h1>
<p>Find me in app/views/welcome/error.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>